server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:mem:testdb?DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    database-platform: H2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        #show_sql: true
        #format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
        page-parameter: page
logging:
  level:
    root: info
    org:
      springframework:
        hibernate:
          SQL: TRACE


