spring:
  data:
    web:
      pageable:
        max-page-size: 200
        default-page-size: 20
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        #default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: trace
#  org:
#    springframework:
#      transaction: trace
# org.hibernate.type: trace