version: '3.1'
services:
  actuator-db:
    image: mysql:8.0.17
    container_name: actuator-db
    command: [ '--default-authentication-plugin=mysql_native_password', '--default-storage-engine=innodb' ]
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=testdb
    ports:
      - 23306:3306